### ISSUE TITLE
Attempting to disable Primitive Tools flint drops breaks drops and can crash

### ISSUE THREAD

**Issue by Exsolutus** [cleverpanda/PrimitiveTools#5]
After setting 'flintDropChance' config option to -1, attempting to disable PrimitiveTools' drops, related block drops are broken. 
 - Breaking gravel with PrimitiveTools spade drops nothing at all.
 - Breaking gravel otherwise drops BOTH gravel and flint every time.
 - Breaking sand drops nothing regardless, and eventually causes a crash:

`java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at panda.primitivetools.common.eventhandler.BlockEvents.onBlockDrops(BlockEvents.java:141)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_BlockEvents_onBlockDrops_HarvestDropsEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:344)
	at net.minecraft.block.Block.func_180653_a(Block.java:572)
	at net.minecraft.block.Block.func_176226_b(Block.java:564)
	at net.minecraft.block.Block.func_180657_a(Block.java:735)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:327)
	at net.minecraft.server.management.PlayerInteractionManager.func_73075_a(PlayerInteractionManager.java:109)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:316)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1734)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by cleverpanda** [comment]
yeah thats expected I guess. added config options 1.2.0+
